### ISSUE TITLE
jupyterhub - open / idle kernels and files

### ISSUE THREAD

**Issue by tlogan2000** [Ouranosinc/pavics-sdi#158] opened 2020-03-19 18:56 UTC
@moulab88 has indicated that user sessions often leave open notebooks (each w/ python process) and open file objects that pile up.   

Is it possible to find a strategy to identify and shutdown idle kernels? 

An associated issue seems to be that all jupyterhub users are seen as a single user on the server (process owner etc) and we therefore ran into the limit of open files (default == 1024)  recently.  @moulab88 has boosted this to 10240 for now on the production server

**Comment by tlogan2000** [comment] 2020-03-19 18:58
Is ther anyone from CRIM we would like to tag on this?

**Comment by tlogan2000** [comment] 2020-03-19 19:07
For the open notebooks  ideally we would like to find a balance between cleaning up processes and letting users runs large / intensive workflows  (multiday analyses on large datasets etc etc)

We can try out best to educate users on shutting down their kernels but I don't know if we will have huge success.

**Comment by dbyrns** [comment] 2020-03-19 19:14
Maybe we should explore the session expiration track. If the user is actively using the platform then the token should renew itself, but without activity the token expired and the ressources associated with the session could then be released. 
I don't think that we should allow multiday analyses running in the notebook directly, we will provide tools to send those tasks in the backend and run asynchronously.

**Comment by tlvu** [comment] 2020-03-19 20:58
This looks promising https://github.com/jupyterhub/jupyterhub/tree/master/examples/cull-idle hope it does what we want, to explore.

**Comment by tlvu** [comment] 2020-03-19 21:16
> all jupyterhub users are seen as a single user on the server (process owner etc)

Because they all run the same docker image with the same internal user "Jenkins" with uuid 1000.  If uuid 1000 happen to be a real user on the host, then it looks like all the jupyter processes belongs to that user and the ulimit of that user is used.

We need to be able to identify to which container belongs a process, then we know who is the real Jupyter user.

We basically need a container aware monitoring system.

**Comment by tlogan2000** [comment] 2020-03-20 13:43
> This looks promising https://github.com/jupyterhub/jupyterhub/tree/master/examples/cull-idle hope it does what we want, to explore.

@tlvu it definitely seems close to what we would want ,... nice find

**Comment by tlvu** [comment] 2020-09-18 18:15
Duplicate of https://github.com/bird-house/birdhouse-deploy/issues/67, closing this one.

**Closed by tlvu** 2020-09-18 18:15 UTC
