### ISSUE TITLE
Birds are likely to generate outputs files with spaces

### ISSUE THREAD

**Issue by dbyrns** [Ouranosinc/pavics-sdi#54] opened 2018-05-15 13:48 UTC
We should investigate on that a little bit more and probably raise an issue on the PyWPS side since the output urls are generated there. They should be url encoded.

**Comment by huard** [comment] 2019-08-19 19:07
@davidcaron Do you think this is still relevant ? Should we fix this in PyWPS ?

**Comment by davidcaron** [comment] 2019-08-19 19:16
From the top of my head I can't remember a time when a pywps service produced a filename containing a space, so I can't say if that's still an issue. It wouldn't be too hard to reproduce though. 

But if the link provided in the status document is not url encoded, it wouldn't work, so I think that unless it has been specifically fixed, it would still be an issue.

**Comment by huard** [comment] 2020-03-12 13:45
@davidcaron If this is still an issue, could you open a ticket on PyWPS ?

**Comment by huard** [comment] 2020-03-16 17:35
I confirm this is an issue in the latest Finch (0.4.1)

**Comment by huard** [comment] 2020-03-16 17:39
https://github.com/geopython/pywps/issues/524

**Comment by huard** [comment] 2021-02-12 19:04
Closing here since issue tracked on PyWPS.

**Closed by huard** 2021-02-12 19:04 UTC
