### ISSUE TITLE
Frontend Features non-functional

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/pavics-sdi#32] opened 2018-04-03 15:18 UTC
Logged on a few PAVICS servers at CRIM and Ouranos and noticed many of the features are not operational today.

- Facets can be searched on some servers but return no results. Other servers detail no facets found.
- When visualizing nc files associated with existing projects (e.g. on Boreas), the temporal slider manipulation is non-functional.
- Workflows that are already set-up (Demo Projects) that point to existing data seem to be running fine until they demand data from server or rely on a process from flyingpigeon:

`0:04:05 10%: Subsetting-proc10-data2: ERROR: Process error: wps_subset_WFS.py._handler Line 79 Traceback (most recent call last): File "/opt/birdhouse/src/flyingpigeon/flyingpigeon/processes/wps_subset_WFS.py", line 76, in _handler result = wfs_common(request, response, mode='subsetter') File "/opt/birdhouse/src/flyingpigeon/flyingpigeon/handler_common.py", line 76, in wfs_common raise Exception(msg) Exception: Failed to fetch features. geoserver: http://boreas.ouranos.ca:8087/geoserver/wfs typename: ADMINBOUNDARIES:canada_admin_boundaries features [u'canada_admin_boundaries.5'] Unknown namespace [ADMINBOUNDARIES] code=NoApplicableCode locator=None)`

**Comment by Renaud009** [comment] 2018-04-25 15:05
Some issues on boreas deployment are due to the fact that outarde project database was copied to boreas, so contained dataset url are pointing to outarde still.
Creating a brand new project should make visualization/timeslider work
The sample workflow seems to fail because ADMINBOUNDARIES not found on your instance of geoserver...

**Comment by Zeitsperre** [comment] 2018-04-25 17:28
Right. That makes a lot of sense. Also explains why that catalog is pointing to non-existent files. Thanks for the clarifications. Is there a reliable method of purging these workflows, seeing as they aren't relevant to the server?

**Comment by Renaud009** [comment] 2018-04-25 17:42
I would prefer having a minimum set of data always deployed and accessible (publicly) on various instances that would include:
- providers with minimal set of processes for each of them
- minimal set of datasets/files/folders
- default permissions on the default data
- minimal set of regions/shapefiles on geoserver
- a set of working workflows templates for each created project (to help user actually build a complex workflow or test monitoring)

That would help me very much as well with integration/functional testings that I'm working on right now. Such data (documented!) is required to be able to launch those tests and to conclude: The platform at this URL is working as intended.

@huard Your thoughts on this?
@dbyrns Your thoughts on this?

**Comment by dbyrns** [comment] 2018-04-25 17:58
I agree with you. I take for granted that boreas should at least contains all the data (datasets, regions, shapefile) found on CRIM birds.
On the other hand we should cherry picked some of the relevant data from boreas to achieve the proposed user stories on our server too. For that, I already create 2 issues : 
https://github.com/Ouranosinc/PAVICS/issues/63
https://github.com/Ouranosinc/PAVICS/issues/64
If something else is missing please create issues accordingly.
For the providers, the docker-compose should take care that we have the same birds/process everywhere.
For the workflows, once validated https://github.com/Ouranosinc/PAVICS/issues/60 should become a good baseline. Once we have something working well, we could add more workflows too.

**Comment by Zeitsperre** [comment] 2018-04-25 18:01
That's a reasonable request. I can speak with @huard later today about which example data sets should be standard across all deployments. Would be great if we could add this example data to the git/docker image so it<s there by default but we might only be able to add fully open/redistributable data sets (e.g. Open Canada and Données Québec Ouvertes; see: https://www.donneesquebec.ca/recherche/fr/dataset/base-de-donnees-geographiques-et-administratives-a-lechelle-de-1-5-000-000) and whichever climate data sets that we have distribution rights to. I can start building a short list of example data we could consider.

**Comment by Renaud009** [comment] 2018-04-25 18:14
@huard @Zeitsperre  Concerning purging workflows (or more generally all project data) on boreas. Is it fine if I delete all existing projects or you guys need some of them for demo or anything else?

**Comment by Renaud009** [comment] 2018-04-27 14:17
Unable to completely test working workflow since we have problems with the mallefowl provider on phoenix https://boreas.ouranos.ca/phoenix/processesList?provider=malleefowl, returns an expcetion

**Comment by huard** [comment] 2018-04-27 19:27
De mon côté boreas dit "Connecting" mais ne se connecte pas...

**Comment by dbyrns** [comment] 2018-05-01 13:40
I will look at that today.

**Comment by dbyrns** [comment] 2018-05-08 18:05
Ok I checked and the thredds download input is an empty catalog... Thus returning an empty array which the parallel group ignore (as designed)

**Comment by dbyrns** [comment] 2018-05-11 15:20
Known issue with flyingpigeon... local files are no more supported... let me edit this workflow for you

**Comment by dbyrns** [comment] 2018-05-11 15:36
```
https://colibri.crim.ca/twitcher/ows/proxy/malleefowl/wps?service=WPS&request=execute&version=1.0.0&identifier=thredds_urls&storeExecuteResponse=true&DataInputs=url=https://colibri.crim.ca/thredds/birdhouse/ncep/cfsr/pr/catalog.xml
{
	"name": "Test1",
	"tasks": [
		{
			"name": "Fetching_catalog",
			"identifier": "thredds_urls",
			"inputs": {
				"url": "https://pavics.ouranos.ca/thredds/catalog/birdhouse/CCCMA/CanCM4/historical/mon/atmos/r9i1p1/pr/catalog.xml"
			},
			"progress_range": [
				0,
				40
			],
			"provider": "malleefowl"
		}
	],
	"parallel_groups": [
		{
			"name": "SubsetterGroup",
			"max_processes": 2,
			"map": {
				"task": "Downloading",
				"output": "output",
				"as_reference": false
			},
			"reduce": {
				"task": "Indexing",
				"output": "crawler_result",
				"as_reference": false
			},
			"tasks": [
				{
					"name": "Subsetting",
					"identifier": "subset_WFS",
					"inputs": {
						"typename": "usa:states",
						"featureids": "usa_admin_boundaries:1",
						"mosaic": "True"
					},
					"linked_inputs": {
						"resource": {
							"task": "SubsetterGroup"
						}
					},
					"progress_range": [
						40,
						80
					],
					"provider": "flyingpigeon"
				},
				{
					"name": "Indexing",
					"identifier": "pavicrawler",
					"linked_inputs": {
						"target_files": {
							"task": "Subsetting",
							"output": "output",
							"as_reference": true
						}
					},
					"progress_range": [
						80,
						100
					],
					"provider": "catalog"
				}
			]
		}
	]
}
```

**Comment by dbyrns** [comment] 2018-05-11 16:29
Simple workflow without crawling : 

```
{
	"name": "Test1",
	"tasks": [
		{
			"name": "Fetching_catalog",
			"identifier": "thredds_urls",
			"inputs": {
				"url": "https://pavics.ouranos.ca/thredds/catalog/birdhouse/CCCMA/CanCM4/historical/mon/atmos/r9i1p1/pr/catalog.xml"
			},
			"progress_range": [
				0,
				40
			],
			"provider": "malleefowl"
		}
	],
	"parallel_groups": [
		{
			"name": "SubsetterGroup",
			"max_processes": 2,
			"map": {
				"task": "Fetching_catalog",
				"output": "output",
				"as_reference": false
			},
			"reduce": {
				"task": "Subsetting",
				"output": "output",
				"as_reference": true
			},
			"tasks": [
				{
					"name": "Subsetting",
					"identifier": "subset_WFS",
					"inputs": {
						"typename": "scratchTJS:canada_admin_boundaries",
						"featureids": "canada_admin_boundaries.5",
						"mosaic": "True"
					},
					"linked_inputs": {
						"resource": {
							"task": "SubsetterGroup"
						}
					},
					"progress_range": [
						40,
						100
					],
					"provider": "flyingpigeon"
				}
			]
		}
	]
}
```

**Comment by Renaud009** [comment] 2018-05-16 15:04
Launched processes with success as well as worfklow on boreas.
Monitoring will be more functionnal when frontend:1.0.5 deployed.
Closing since most features are now functionnals on boreas.

**Closed by Renaud009** 2018-05-16 15:04 UTC
Labels: UI, bug
