### ISSUE TITLE
Process errors in flyingpigeon

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-sdi#43] opened 2018-05-02 13:45 UTC
Trying to understand why tests pass locally but fail run remotely. 

Using a thredds URL as input for a process run locally, the error log shows: 
```
2018-05-02 09:35:46,284] [ERROR] line=275 module=Process Process error: wps_subset_countries.py._handler Line 98 [Errno 2] No such file or directory
```
Line 98 is a call to 
```
def rename_complexinputs(complexinputs):
    """
    TODO: this method is just a dirty workaround to rename input files according to the url name.
    """
    resources = []
    for inpt in complexinputs:
        new_name = inpt.url.split('/')[-1]
        os.rename(inpt.file, new_name)
        resources.append(os.path.abspath(new_name))
    return resources
```

**Comment by huard** [comment] 2018-05-02 15:26
It seems that FP fails, but the status remains `ProcessAccepted` and no error is reported back in owslib.

**Comment by cehbrecht** [comment] 2018-05-02 16:41
@huard I guess the `rename_complexinputs` method was meant to keep the "original" filename of the inputs. But this should not be necessary anymore. It is fixed in pywps:
https://github.com/geopython/pywps/pull/259

**Comment by dbyrns** [comment] 2018-05-02 20:05
PyWPS is supposed to download remote files I think. Otherwise Blaise made modification to support OpenDAP format so that the file doesn't need to be available locally. I don't think I can help a lot here since I never worked with flyingpigeon before. If I get some spare time I could look at that but I already have a good backlog.

**Comment by huard** [comment] 2018-05-02 20:56
Agreed, and I think it's more related to pywps than flyingpigeon. I'll check this out with Carsten.

**Comment by dbyrns** [comment] 2018-05-03 12:59
Ok if you can resolve that on your side that will be a huge plus for us because we don't have a lot of people available to work on the backend right now (should be better starting next week)

**Comment by cehbrecht** [comment] 2018-05-03 14:49
@huard PyWPS downloads the input resource provided by a URL and makes the file locally available in the processing temp-folder. Your should access it with:
```
request.inputs['resource'][0].file     # file access
request.inputs['resource'][0].data   # data stream access
```

The `url` property should also exist (haven't found the code yet in pywps) and will probably show the URL provided by the request. To access the resource you should use `file` or `data`. 

OpenDAP URLs will not work with ComplexInputs unless we make changes to PyWPS: 
https://github.com/geopython/pywps/issues/152 

Which process troubles you? Can I check it on my side? What is the input URL?

**Comment by dbyrns** [comment] 2018-05-03 15:29
@huard I confirmed with @Zvax that if the datatype is a string the frontend will fill the parameter with the OpenDAP url, but if its a complexdata it will use the direct download url. 
We only need to take care with the current naming convention : 
https://github.com/Ouranosinc/PAVICS-frontend/blob/master/src/constants.js#L42-L45

**Comment by huard** [comment] 2018-05-03 19:32
My problems are not with the frontend, but with a simple owslib call to the process. 
```
wps = WebProcessingService('http://localhost:5000/wps')
def check_subset_countries(wps):
    anon_href = "https://pluvier.crim.ca/twitcher/ows/proxy/thredds/fileServer/birdhouse/CMIP5/CCCMA/CanESM2/historical/mon/atmos/r1i1p1/pr/pr_Amon_CanESM2_historical_r1i1p1_185001-200512.nc"

    return wps.execute('subset_countries', inputs=[("resource", anon_href), ("region", "CAN"), ])
```
which fails because the url attribute is left empty.

**Comment by cehbrecht** [comment] 2018-05-04 15:58
@huard I'm still holding back a patch to pywps to pass credentials to an ESGF OpenDAP service using a `.dodsrc` config. But the patch doesn't feel right. If you open a ticket on pywps we can work on a common solution.

With OWSLib you can also send header variables to the WPS service (tokens etc):
https://github.com/geopython/OWSLib/blob/12737e465a7965bfb24528d68669d387d760c22a/owslib/wps.py#L209

**Comment by dbyrns** [comment] 2018-05-04 16:16
@cehbrecht we already add a patch to handle opendap auth (per process basis though):
https://github.com/Ouranosinc/flyingpigeon/commit/531c8a930620202607a5295bbb05dc3d9c3691ca
Unfortunately I saw that the cookie name is hard-coded.

Having that built-in in PyWPS would be welcome.

But we also have a need to pass credentials for direct download too. For that we will need to modify the function referenced here : https://github.com/geopython/pywps/blob/master/pywps/app/Service.py#L444

**Comment by dbyrns** [comment] 2018-05-04 21:15
@ldperron I made some tests today and the process being stuck in the accepted state is not reproducible everywhere. Outarde is stuck in that state, but if I run a local or an hirondelle deployment of flyingpigeon the process complete successfully. Both hirondelle and outarde config look up to date though so I'm not sure why it's working on hirondelle and not on outarde.

Here is a code snippet that can be run to test a process of flyingpigeon : 

[test_fly.txt](https://github.com/Ouranosinc/pavics-sdi/files/1975915/test_fly.txt)

**Comment by ldperron** [comment] 2018-05-07 13:42
@dbyrns Sorry for not letting everyone know, I found the root cause of the issues with WPS processes.... running gunicorn with --max-requests 1 breaks the async processes in pyWPS. Fix is manually implemented on hirondelle, will commit permanent fix today, and deploy on all birds, including Boreas.

**Comment by ldperron** [comment] 2018-05-08 16:12
I added to the PAVICS project a script to check/clean/zap the pywps databases:
/PAVICS/birdhouse/scripts/check-wps-database.sh
Just run it without arguments for help

**Comment by Zeitsperre** [comment] 2018-05-08 17:34
@cehbrecht does the SQLite limitation extend to polygons loaded into GeoServer? @tlogan2000 and I are looking into using the GeoPackage standard based on SQLite3 for much easier/scripted shapefile loading. Do the issues with PyWPS extend to it?

**Comment by cehbrecht** [comment] 2018-05-08 20:17
@Zeitsperre I'm not so familiar with sqlite. I just know that it does not handle access by parallel processes well. This should be documented in the sqlite docu. This is at least one reason why dead processes fill up the database.

Here are some links I have found:
* https://github.com/geopython/pywps/issues/217
* https://stackoverflow.com/questions/4060772/sqlite-concurrent-access

**Comment by dbyrns** [comment] 2018-05-09 15:57
@Zeitsperre I'm not sure why GeoServer came up in this thread but the issue with the database backend (sqlite or postgres) is related to the design of PyWPS, maybe GeoServer is doing a better usage of SQLite by avoiding concurrent accesses.

**Comment by tomLandry** [comment] 2018-05-09 16:06
If you have direct questions to GeoServer devs, I can ask in OGC TB14 as GeoSolutions is very much involved.

**Comment by Zeitsperre** [comment] 2018-05-09 16:13
@tomLandry I definitely do. I'll see if I can write up a few questions in the next week or so. Thanks!

**Closed** 2018-06-20 13:35 UTC
